def inputOutput():
    print("Enter a String")
    str = input()
    print("Enter an Integer Number")
    num = int(input())
    print("Enter A Fractional Number")
    fraction = float(input())
    print("Entered String is", str)
    print("Entered Number is", num)
    print("Entered Fraction is", fraction)
